Vagrant.configure("2") do |config|
  # Base box
  config.vm.box = "ubuntu/jammy64"

  # VM provider settings
  config.vm.provider "virtualbox" do |vb|
    vb.name   = "my_VM"
    vb.memory = 4096                # 4 GB RAM
    vb.cpus   = 2
    vb.gui    = false                      # Disable GUI for headless mode
  end

  # Networking
  config.vm.network "private_network", ip: "192.168.56.10"

  # Shared folder (host <-> guest sync)
  config.vm.synced_folder "./", "/vagrant", type: "virtualbox"

end